
POST http://localhost:3000/api/auth/login
Content-Type: application/json

    {
      "username": "newuser",
      "password": "password123"
    }
###
    
POST http://localhost:3000/api/login
Content-Type: application/json

###
POST http://localhost:3000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJ1c2VybmFtZSI6InRlc3QiLCJlbWFpbCI6Impvc2hAZ21haWwuY29tIn0sImlhdCI6MTc2ODY1MTQzMSwiZXhwIjoxNzY4NjUxNDQ2fQ.5TcGOdv6d-8OsCewkCAslXsRBJrkn5zq8YDnO6TT5To
